package main

import (
	"flag"
	"fmt"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/types/pluginpb"
)

var showVersion = flag.Bool("version", false, "print version and exit")

func main() {
	flag.Parse()
	if *showVersion {
		fmt.Printf("protoc-gen-go-kernel %s (generates github.com/aisphereio/kernel/serverx service modules)\n", release)
		return
	}
	protogen.Options{ParamFunc: flag.CommandLine.Set}.Run(func(gen *protogen.Plugin) error {
		gen.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)
		for _, f := range gen.Files {
			if f.Generate {
				generateFile(gen, f)
			}
		}
		return nil
	})
}

func generateFile(gen *protogen.Plugin, file *protogen.File) {
	if len(file.Services) == 0 {
		return
	}
	filename := file.GeneratedFilenamePrefix + "_kernel.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	g.P("// Code generated by protoc-gen-go-kernel. DO NOT EDIT.")
	g.P("// versions:")
	g.P("// - protoc-gen-go-kernel ", release)
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	serverxPkg := protogen.GoImportPath("github.com/aisphereio/kernel/serverx")
	for _, svc := range file.Services {
		genServiceKernelModule(g, serverxPkg, svc)
	}
}

func genServiceKernelModule(g *protogen.GeneratedFile, serverxPkg protogen.GoImportPath, svc *protogen.Service) {
	fn := svc.GoName + "KernelModule"
	g.P("// ", fn, " returns the generated Kernel service module for ", svc.Desc.FullName(), ".")
	g.P("func ", fn, "() ", serverxPkg.Ident("ServiceModule"), " {")
	g.P("return ", serverxPkg.Ident("ServiceModule"), "{")
	g.P("Name: ", fmt.Sprintf("%q", defaultServiceName(string(svc.Desc.FullName()))), ",")
	g.P("GatewayManifest: ", svc.GoName, "GatewayManifest(),")
	g.P("RequestInfoResolver: ", svc.GoName, "RequestInfoResolver,")
	g.P("AccessResolver: ", svc.GoName, "AccessResolver,")
	g.P("}")
	g.P("}")
	g.P()
}

func defaultServiceName(full string) string {
	full = strings.TrimSpace(full)
	if full == "" {
		return "service"
	}
	parts := strings.Split(full, ".")
	name := parts[len(parts)-1]
	name = strings.TrimSuffix(name, "Service")
	if name == "" {
		name = parts[len(parts)-1]
	}
	return strings.ToLower(kebab(name)) + "-service"
}

func kebab(s string) string {
	var b strings.Builder
	for i, r := range s {
		if r == '.' || r == '_' || r == ' ' {
			b.WriteByte('.')
			continue
		}
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				b.WriteByte('.')
			}
			b.WriteRune(r + ('a' - 'A'))
			continue
		}
		b.WriteRune(r)
	}
	return strings.ReplaceAll(strings.Trim(b.String(), "."), "..", ".")
}
