package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/types/pluginpb"

	"github.com/aisphereio/kernel/internal/protooptions"
)

var showVersion = flag.Bool("version", false, "print version and exit")

func main() {
	flag.Parse()
	if *showVersion {
		fmt.Printf("protoc-gen-go-authz %s (generates github.com/aisphereio/kernel/authz helpers)\n", release)
		return
	}
	protogen.Options{ParamFunc: flag.CommandLine.Set}.Run(func(gen *protogen.Plugin) error {
		gen.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)
		for _, f := range gen.Files {
			if f.Generate {
				generateFile(gen, f)
			}
		}
		return nil
	})
}

type rule struct {
	Service    string `json:"service"`
	Method     string `json:"method"`
	FullMethod string `json:"full_method"`
	Action     string `json:"action"`
	Resource   string `json:"resource"`
	Audience   string `json:"audience"`
	Mode       string `json:"mode"`
	AuditEvent string `json:"audit_event,omitempty"`
	AuditRisk  string `json:"audit_risk,omitempty"`
	Capability string `json:"capability,omitempty"`
}

type methodRule struct {
	method *protogen.Method
	rule   rule
}

func generateFile(gen *protogen.Plugin, file *protogen.File) {
	services := collectRules(file)
	if len(services) == 0 {
		return
	}
	filename := file.GeneratedFilenamePrefix + "_authz.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	g.P("// Code generated by protoc-gen-go-authz. DO NOT EDIT.")
	g.P("// versions:")
	g.P("// - protoc-gen-go-authz ", release)
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	authzPkg := protogen.GoImportPath("github.com/aisphereio/kernel/authz")
	contextxPkg := protogen.GoImportPath("github.com/aisphereio/kernel/contextx")
	contextPkg := protogen.GoImportPath("context")
	grpcPkg := protogen.GoImportPath("google.golang.org/grpc")
	stringsPkg := protogen.GoImportPath("strings")
	_ = contextPkg
	g.P("var _ = ", grpcPkg.Ident("EmptyCallOption"), "{}")
	g.P()

	for _, svc := range file.Services {
		mrs := services[svc.GoName]
		if len(mrs) == 0 {
			continue
		}
		genRules(g, authzPkg, svc, mrs)
		genManifest(g, svc, mrs)
		genSecureClient(g, authzPkg, contextxPkg, contextPkg, grpcPkg, stringsPkg, svc, mrs)
	}
}

func collectRules(file *protogen.File) map[string][]methodRule {
	out := map[string][]methodRule{}
	for _, svc := range file.Services {
		for _, m := range svc.Methods {
			r, ok := parseMethodRule(svc, m)
			if ok {
				out[svc.GoName] = append(out[svc.GoName], methodRule{method: m, rule: r})
			}
		}
	}
	return out
}

func parseMethodRule(svc *protogen.Service, m *protogen.Method) (rule, bool) {
	opts := m.Desc.Options()
	if opts == nil {
		return rule{}, false
	}
	unknown := opts.ProtoReflect().GetUnknown()
	authzPayload, ok := protooptions.LastExtensionPayload(unknown, protooptions.ExtAuthz)
	if !ok {
		return rule{}, false
	}
	a := protooptions.ParseAuthz(authzPayload)
	if a.Action == "" && a.Resource == "" && a.Audience == "" {
		return rule{}, false
	}
	r := rule{
		Service:    string(svc.Desc.FullName()),
		Method:     string(m.Desc.Name()),
		FullMethod: "/" + string(svc.Desc.FullName()) + "/" + string(m.Desc.Name()),
		Action:     a.Action,
		Resource:   a.Resource,
		Audience:   a.Audience,
		Mode:       modeName(int(a.Mode)),
	}
	if r.Mode == "" {
		r.Mode = "CHECK_ONLY"
	}
	if payload, ok := protooptions.LastExtensionPayload(unknown, protooptions.ExtAudit); ok {
		audit := protooptions.ParseAudit(payload)
		r.AuditEvent = audit.Event
		r.AuditRisk = audit.Risk
	}
	if payload, ok := protooptions.LastExtensionPayload(unknown, protooptions.ExtCapability); ok {
		cap := protooptions.ParseCapability(payload)
		if cap.Group != "" && cap.Name != "" {
			r.Capability = cap.Group + "." + cap.Name
		} else {
			r.Capability = firstNonEmpty(cap.Name, cap.Group)
		}
	}
	return r, true
}

func genRules(g *protogen.GeneratedFile, authzPkg protogen.GoImportPath, svc *protogen.Service, mrs []methodRule) {
	g.P("var ", svc.GoName, "AuthzRules = ", authzPkg.Ident("Rules"), "{")
	for _, mr := range mrs {
		r := mr.rule
		g.P(fmt.Sprintf("%q", r.FullMethod), ": {")
		g.P("Service: ", fmt.Sprintf("%q", r.Service), ",")
		g.P("Method: ", fmt.Sprintf("%q", r.Method), ",")
		g.P("FullMethod: ", fmt.Sprintf("%q", r.FullMethod), ",")
		g.P("Action: ", fmt.Sprintf("%q", r.Action), ",")
		g.P("Resource: ", fmt.Sprintf("%q", r.Resource), ",")
		g.P("Audience: ", fmt.Sprintf("%q", r.Audience), ",")
		g.P("Mode: ", authzPkg.Ident("RuleMode"), "(", fmt.Sprintf("%q", r.Mode), "),")
		if r.AuditEvent != "" {
			g.P("AuditEvent: ", fmt.Sprintf("%q", r.AuditEvent), ",")
		}
		if r.AuditRisk != "" {
			g.P("AuditRisk: ", fmt.Sprintf("%q", r.AuditRisk), ",")
		}
		if r.Capability != "" {
			g.P("Capability: ", fmt.Sprintf("%q", r.Capability), ",")
		}
		g.P("},")
	}
	g.P("}")
	g.P()
}

func genManifest(g *protogen.GeneratedFile, svc *protogen.Service, mrs []methodRule) {
	list := make([]rule, 0, len(mrs))
	for _, mr := range mrs {
		list = append(list, mr.rule)
	}
	b, _ := json.MarshalIndent(map[string]any{"service": string(svc.Desc.FullName()), "methods": list}, "", "  ")
	g.P("const ", svc.GoName, "AuthzManifestJSON = `", string(b), "`")
	g.P()
}

func genSecureClient(g *protogen.GeneratedFile, authzPkg, contextxPkg, contextPkg, grpcPkg, stringsPkg protogen.GoImportPath, svc *protogen.Service, mrs []methodRule) {
	ruleMethods := map[string]rule{}
	for _, mr := range mrs {
		ruleMethods[mr.method.GoName] = mr.rule
	}
	clientName := svc.GoName + "SecureClient"
	g.P("type ", clientName, " struct {")
	g.P("raw ", svc.GoName, "Client")
	g.P("guard ", authzPkg.Ident("Guard"))
	g.P("resolver ", authzPkg.Ident("RuleResolver"))
	g.P("}")
	g.P()
	g.P("func New", clientName, "(raw ", svc.GoName, "Client, guard ", authzPkg.Ident("Guard"), ") *", clientName, " {")
	g.P("return &", clientName, "{raw: raw, guard: guard, resolver: ", authzPkg.Ident("RuleResolver"), "{}}")
	g.P("}")
	g.P()
	g.P("var _ ", svc.GoName, "Client = (*", clientName, ")(nil)")
	g.P()
	for _, m := range svc.Methods {
		r, hasRule := ruleMethods[m.GoName]
		if !m.Desc.IsStreamingClient() && !m.Desc.IsStreamingServer() {
			g.P("func (c *", clientName, ") ", m.GoName, "(ctx ", contextPkg.Ident("Context"), ", in *", m.Input.GoIdent, ", opts ...", grpcPkg.Ident("CallOption"), ") (*", m.Output.GoIdent, ", error) {")
			if hasRule {
				g.P("if c != nil && c.guard != nil {")
				g.P("rule := ", svc.GoName, "AuthzRules[", fmt.Sprintf("%q", r.FullMethod), "]")
				g.P("resource, err := c.resolver.ResolveResource(rule, in)")
				g.P("if err != nil { return nil, err }")
				g.P("subject := ", helperName(svc), "SubjectFromContext(ctx)")
				g.P("switch rule.Mode {")
				g.P("case ", authzPkg.Ident("RuleModeScopedToken"), ":")
				g.P("token, decision, err := c.guard.RequireScopedToken(ctx, ", authzPkg.Ident("ScopedTokenRequest"), "{Subject: subject, Action: rule.Action, Resource: resource, Audience: rule.Audience, Rule: rule, TenantID: ", contextxPkg.Ident("TenantFromContext"), "(ctx)})")
				g.P("if err != nil { return nil, err }")
				g.P("if decision.ConsistencyToken != \"\" { ctx = ", contextxPkg.Ident("WithAuthzDecisionID"), "(ctx, decision.ConsistencyToken) }")
				g.P("if token != \"\" { ctx = ", contextxPkg.Ident("WithScopedToken"), "(ctx, token) }")
				g.P("case ", authzPkg.Ident("RuleModeCheckOnly"), ":")
				g.P("decision, err := c.guard.Require(ctx, ", authzPkg.Ident("CheckRequest"), "{Subject: subject, Resource: resource, Permission: rule.Action, TenantID: ", contextxPkg.Ident("TenantFromContext"), "(ctx)})")
				g.P("if err != nil { return nil, err }")
				g.P("if decision.ConsistencyToken != \"\" { ctx = ", contextxPkg.Ident("WithAuthzDecisionID"), "(ctx, decision.ConsistencyToken) }")
				g.P("case ", authzPkg.Ident("RuleModeSelfCheck"), ":")
				g.P("// SELF_CHECK means the target resource service performs the final check.")
				g.P("case ", authzPkg.Ident("RuleModeUnspecified"), ":")
				g.P("return nil, ", authzPkg.Ident("ErrInvalidRequest"), "(\"authz rule mode must not be UNSPECIFIED\")")
				g.P("default:")
				g.P("return nil, ", authzPkg.Ident("ErrInvalidRequest"), "(\"unsupported authz rule mode: \" + string(rule.Mode))")
				g.P("}")
				g.P("}")
			}
			g.P("return c.raw.", m.GoName, "(ctx, in, opts...)")
			g.P("}")
			g.P()
			continue
		}
		if m.Desc.IsStreamingClient() {
			g.P("func (c *", clientName, ") ", m.GoName, "(ctx ", contextPkg.Ident("Context"), ", opts ...", grpcPkg.Ident("CallOption"), ") (", svc.GoName, "_", m.GoName, "Client, error) {")
			g.P("return c.raw.", m.GoName, "(ctx, opts...)")
			g.P("}")
			g.P()
		} else {
			g.P("func (c *", clientName, ") ", m.GoName, "(ctx ", contextPkg.Ident("Context"), ", in *", m.Input.GoIdent, ", opts ...", grpcPkg.Ident("CallOption"), ") (", svc.GoName, "_", m.GoName, "Client, error) {")
			g.P("return c.raw.", m.GoName, "(ctx, in, opts...)")
			g.P("}")
			g.P()
		}
	}
	g.P("func ", helperName(svc), "SubjectFromContext(ctx ", contextPkg.Ident("Context"), ") ", authzPkg.Ident("SubjectRef"), " {")
	g.P("p := ", contextxPkg.Ident("PrincipalFromContext"), "(ctx)")
	g.P("if p == nil { return ", authzPkg.Ident("SubjectRef"), "{} }")
	g.P("typ := ", authzPkg.Ident("SubjectTypeUser"))
	g.P("if ", stringsPkg.Ident("HasPrefix"), "(p.SubjectID, \"svc:\") { typ = ", authzPkg.Ident("SubjectTypeService"), " }")
	g.P("return ", authzPkg.Ident("SubjectRef"), "{Type: typ, ID: p.SubjectID}")
	g.P("}")
	g.P()
}

func helperName(svc *protogen.Service) string { return "_" + svc.GoName + "Authz" }

func modeName(v int) string {
	switch v {
	case 1:
		return "CHECK_ONLY"
	case 2:
		return "SCOPED_TOKEN"
	case 3:
		return "SELF_CHECK"
	default:
		return "UNSPECIFIED"
	}
}

func firstNonEmpty(values ...string) string {
	for _, v := range values {
		if strings.TrimSpace(v) != "" {
			return strings.TrimSpace(v)
		}
	}
	return ""
}
