package main

import (
	"flag"
	"fmt"
	"net/http"
	"strings"

	"github.com/aisphereio/kernel/internal/protooptions"
	"google.golang.org/genproto/googleapis/api/annotations"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/pluginpb"
)

var showVersion = flag.Bool("version", false, "print version and exit")

func main() {
	flag.Parse()
	if *showVersion {
		fmt.Printf("protoc-gen-go-gateway %s (generates github.com/aisphereio/kernel/gatewayx route manifests)\n", release)
		return
	}
	protogen.Options{ParamFunc: flag.CommandLine.Set}.Run(func(gen *protogen.Plugin) error {
		gen.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)
		for _, f := range gen.Files {
			if f.Generate {
				generateFile(gen, f)
			}
		}
		return nil
	})
}

type routeSpec struct {
	ServiceFullName string
	ServiceGoName   string
	MethodGoName    string
	MethodName      string
	InputGoIdent    protogen.GoIdent
	FullMethod      string
	HTTPMethod      string
	Path            string
	Exposure        int32
	Audience        string
	Protocol        string
	PathVars        []pathVar
}

type pathVar struct {
	Name        string
	FieldGoName string
}

func generateFile(gen *protogen.Plugin, file *protogen.File) {
	routesBySvc := collectGatewayRoutes(file)
	if len(routesBySvc) == 0 {
		return
	}
	filename := file.GeneratedFilenamePrefix + "_gateway.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	g.P("// Code generated by protoc-gen-go-gateway. DO NOT EDIT.")
	g.P("// versions:")
	g.P("// - protoc-gen-go-gateway ", release)
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	gatewayxPkg := protogen.GoImportPath("github.com/aisphereio/kernel/gatewayx")
	accessv1Pkg := protogen.GoImportPath("github.com/aisphereio/kernel/api/aisphere/access/v1")
	for _, svc := range file.Services {
		routes := routesBySvc[svc.GoName]
		if len(routes) == 0 {
			continue
		}
		genServiceManifest(g, gatewayxPkg, accessv1Pkg, svc, routes)
		genServiceBindings(g, gatewayxPkg, svc, routes)
	}
}

func collectGatewayRoutes(file *protogen.File) map[string][]routeSpec {
	out := map[string][]routeSpec{}
	for _, svc := range file.Services {
		for _, m := range svc.Methods {
			rule, ok := proto.GetExtension(m.Desc.Options(), annotations.E_Http).(*annotations.HttpRule)
			if !ok || rule == nil {
				continue
			}
			access := accessPolicy(m)
			all := append([]*annotations.HttpRule{}, rule.AdditionalBindings...)
			all = append(all, rule)
			for _, r := range all {
				method, path := httpBinding(r)
				if path == "" {
					continue
				}
				spec := routeSpec{
					ServiceFullName: string(svc.Desc.FullName()),
					ServiceGoName:   svc.GoName,
					MethodGoName:    m.GoName,
					MethodName:      string(m.Desc.Name()),
					InputGoIdent:    m.Input.GoIdent,
					FullMethod:      "/" + string(svc.Desc.FullName()) + "/" + string(m.Desc.Name()),
					HTTPMethod:      method,
					Path:            path,
					Exposure:        access.Exposure,
					Audience:        strings.TrimSpace(access.Authz.Audience),
					Protocol:        "grpc",
					PathVars:        resolvePathVars(path, m.Input),
				}
				if spec.Exposure == 0 {
					spec.Exposure = 3
				} // default to AUTHORIZED if buf-check is bypassed
				out[svc.GoName] = append(out[svc.GoName], spec)
			}
		}
	}
	return out
}

func accessPolicy(m *protogen.Method) protooptions.AccessPolicy {
	unknown := m.Desc.Options().ProtoReflect().GetUnknown()
	if payload, ok := protooptions.LastExtensionPayload(unknown, protooptions.ExtAccess); ok {
		return protooptions.ParseAccessPolicy(payload)
	}
	return protooptions.AccessPolicy{}
}

func httpBinding(rule *annotations.HttpRule) (string, string) {
	switch p := rule.Pattern.(type) {
	case *annotations.HttpRule_Get:
		return http.MethodGet, p.Get
	case *annotations.HttpRule_Put:
		return http.MethodPut, p.Put
	case *annotations.HttpRule_Post:
		return http.MethodPost, p.Post
	case *annotations.HttpRule_Delete:
		return http.MethodDelete, p.Delete
	case *annotations.HttpRule_Patch:
		return http.MethodPatch, p.Patch
	case *annotations.HttpRule_Custom:
		return strings.ToUpper(p.Custom.Kind), p.Custom.Path
	default:
		return http.MethodPost, ""
	}
}

func genServiceManifest(g *protogen.GeneratedFile, gatewayxPkg, accessv1Pkg protogen.GoImportPath, svc *protogen.Service, routes []routeSpec) {
	fn := svc.GoName + "GatewayManifest"
	g.P("// ", fn, " returns the generated Gateway route manifest for ", svc.Desc.FullName(), ".")
	g.P("func ", fn, "() ", gatewayxPkg.Ident("Manifest"), " {")
	g.P("return ", gatewayxPkg.Ident("Manifest"), "{")
	g.P("Service: ", fmt.Sprintf("%q", defaultServiceName(string(svc.Desc.FullName()))), ",")
	g.P("Namespace: ", fmt.Sprintf("%q", "aisphere"), ",")
	g.P("Routes: []", gatewayxPkg.Ident("GatewayRoute"), "{")
	for _, rt := range routes {
		svcName := rt.Audience
		if svcName == "" {
			svcName = defaultServiceName(rt.ServiceFullName)
		}
		g.P("{")
		g.P("ID: ", fmt.Sprintf("%q", defaultRouteID(rt)), ",")
		g.P("Method: ", fmt.Sprintf("%q", rt.HTTPMethod), ",")
		g.P("Path: ", fmt.Sprintf("%q", rt.Path), ",")
		g.P("Upstream: ", gatewayxPkg.Ident("UpstreamRef"), "{Service: ", fmt.Sprintf("%q", svcName), ", Namespace: ", fmt.Sprintf("%q", "aisphere"), ", Protocol: ", fmt.Sprintf("%q", rt.Protocol), ", Operation: ", fmt.Sprintf("%q", rt.FullMethod), "},")
		g.P("Gateway: ", gatewayxPkg.Ident("GatewayPolicy"), "{Exposure: ", accessv1Pkg.Ident(exposureIdent(rt.Exposure)), ", AuthnMode: ", gatewayxPkg.Ident(authnModeIdent(rt.Exposure)), ", ForwardAuthorization: ", forwardAuth(rt.Exposure), "},")
		g.P("},")
	}
	g.P("},")
	g.P("}")
	g.P("}")
	g.P()
}

func genServiceBindings(g *protogen.GeneratedFile, gatewayxPkg protogen.GoImportPath, svc *protogen.Service, routes []routeSpec) {
	if len(routes) == 0 {
		return
	}
	for _, rt := range routes {
		bindName := svc.GoName + "GatewayBind" + rt.MethodGoName
		g.P("// ", bindName, " binds the matched HTTP Gateway request to the gRPC request for ", rt.FullMethod, ".")
		g.P("func ", bindName, "(req ", gatewayxPkg.Ident("DispatchRequest"), ", match ", gatewayxPkg.Ident("RouteMatch"), ") (*", rt.InputGoIdent, ", error) {")
		g.P("out := &", rt.InputGoIdent, "{}")
		g.P("if v, ok := req.Body.(*", rt.InputGoIdent, "); ok && v != nil { out = v }")
		g.P("if v, ok := req.Body.(", rt.InputGoIdent, "); ok { out = &v }")
		for _, pv := range rt.PathVars {
			g.P("if v := match.Params[", fmt.Sprintf("%q", pv.Name), "]; v != \"\" { out.", pv.FieldGoName, " = v }")
		}
		g.P("return out, nil")
		g.P("}")
		g.P()
	}
	regName := "Register" + svc.GoName + "GatewayInvokers"
	clientType := svc.GoName + "Client"
	g.P("// ", regName, " registers generated Gateway -> gRPC operation invokers for ", svc.Desc.FullName(), ".")
	g.P("func ", regName, "(registry *", gatewayxPkg.Ident("InvokerRegistry"), ", client ", clientType, ") error {")
	for i, rt := range routes {
		prefix := "if err := "
		if i > 0 {
			prefix = "if err := "
		}
		g.P(prefix, "registry.Register(", fmt.Sprintf("%q", rt.FullMethod), ", ", gatewayxPkg.Ident("GRPCUnaryInvoker"), "(", svc.GoName, "GatewayBind", rt.MethodGoName, ", client.", rt.MethodGoName, ")); err != nil { return err }")
	}
	g.P("return nil")
	g.P("}")
	g.P()
}

func resolvePathVars(path string, input *protogen.Message) []pathVar {
	names := extractPathVars(path)
	if len(names) == 0 || input == nil {
		return nil
	}
	fields := map[string]string{}
	for _, f := range input.Fields {
		fields[string(f.Desc.Name())] = f.GoName
		fields[f.Desc.JSONName()] = f.GoName
	}
	out := make([]pathVar, 0, len(names))
	for _, name := range names {
		field := strings.Split(name, "=")[0]
		if goName := fields[field]; goName != "" {
			out = append(out, pathVar{Name: field, FieldGoName: goName})
		}
	}
	return out
}

func extractPathVars(path string) []string {
	var out []string
	for {
		start := strings.Index(path, "{")
		if start < 0 {
			break
		}
		path = path[start+1:]
		end := strings.Index(path, "}")
		if end < 0 {
			break
		}
		name := strings.TrimSpace(path[:end])
		if name != "" {
			out = append(out, name)
		}
		path = path[end+1:]
	}
	return out
}

func defaultServiceName(full string) string {
	full = strings.TrimSpace(full)
	if full == "" {
		return "service"
	}
	parts := strings.Split(full, ".")
	name := parts[len(parts)-1]
	name = strings.TrimSuffix(name, "Service")
	if name == "" {
		name = parts[len(parts)-1]
	}
	return strings.ToLower(kebab(name)) + "-service"
}

func defaultRouteID(rt routeSpec) string {
	svc := strings.TrimSuffix(rt.ServiceGoName, "Service")
	return strings.ToLower(kebab(svc + "." + rt.MethodName))
}

func kebab(s string) string {
	var b strings.Builder
	for i, r := range s {
		if r == '.' || r == '_' || r == ' ' {
			b.WriteByte('.')
			continue
		}
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				b.WriteByte('.')
			}
			b.WriteRune(r + ('a' - 'A'))
			continue
		}
		b.WriteRune(r)
	}
	return strings.ReplaceAll(strings.Trim(b.String(), "."), "..", ".")
}

func exposureIdent(exposure int32) string {
	switch exposure {
	case 1:
		return "Exposure_PUBLIC"
	case 2:
		return "Exposure_AUTHENTICATED"
	case 3:
		return "Exposure_AUTHORIZED"
	case 4:
		return "Exposure_INTERNAL"
	case 5:
		return "Exposure_SYSTEM"
	default:
		return "Exposure_AUTHORIZED"
	}
}

func authnModeIdent(exposure int32) string {
	switch exposure {
	case 1, 5:
		return "AuthnModeNone"
	default:
		return "AuthnModePassive"
	}
}

func forwardAuth(exposure int32) bool { return exposure == 2 || exposure == 3 || exposure == 4 }
