package main

import (
	"bytes"
	"flag"
	"fmt"
	"io"
	"os"
	"regexp"
	"sort"
	"strings"

	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"

	"github.com/aisphereio/kernel/internal/protooptions"
)

const (
	exitDiagnostics = 1
	exitToolError   = 2
)

var (
	descriptorPath = flag.String("descriptor", "-", "FileDescriptorSet path generated by `buf build -o`, or - for stdin")
	showVersion    = flag.Bool("version", false, "print version and exit")
	highRiskCSV    = flag.String("high-risk-actions", "delete,publish,grant,share,transfer,owner,admin,remove,revoke", "comma-separated action substrings that require aisphere.audit")
)

func main() {
	flag.Parse()
	if *showVersion {
		fmt.Println("buf-check-aisphere " + release)
		return
	}

	data, err := readInput(*descriptorPath)
	if err != nil {
		fatal(err)
	}

	var set descriptorpb.FileDescriptorSet
	if err := proto.Unmarshal(data, &set); err != nil {
		fatal(fmt.Errorf("parse descriptor set: %w", err))
	}

	diags := analyze(&set, checkConfig{HighRiskActions: splitCSV(*highRiskCSV)})
	for _, d := range diags {
		fmt.Fprintln(os.Stderr, d)
	}
	if len(diags) > 0 {
		fmt.Fprintf(os.Stderr, "buf-check-aisphere: %d contract violation(s) found\n", len(diags))
		os.Exit(exitDiagnostics)
	}
	fmt.Printf("buf-check-aisphere: checked %d proto files\n", len(set.GetFile()))
}

func readInput(path string) ([]byte, error) {
	if path == "" || path == "-" {
		return io.ReadAll(os.Stdin)
	}
	return os.ReadFile(path)
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "buf-check-aisphere:", err)
	os.Exit(exitToolError)
}

type checkConfig struct {
	HighRiskActions []string
}

type analyzer struct {
	messages map[string]*descriptorpb.DescriptorProto
	config   checkConfig
}

func analyze(set *descriptorpb.FileDescriptorSet, config checkConfig) []string {
	a := &analyzer{messages: indexMessages(set), config: config}
	var diags []string
	for _, f := range set.GetFile() {
		if skipFile(f.GetName()) {
			continue
		}
		pkg := f.GetPackage()
		for _, svc := range f.GetService() {
			for _, method := range svc.GetMethod() {
				diags = append(diags, a.checkMethod(f.GetName(), pkg, svc, method)...)
			}
		}
	}
	sort.Strings(diags)
	return diags
}

func indexMessages(set *descriptorpb.FileDescriptorSet) map[string]*descriptorpb.DescriptorProto {
	messages := map[string]*descriptorpb.DescriptorProto{}
	for _, f := range set.GetFile() {
		if skipFile(f.GetName()) {
			continue
		}
		pkg := f.GetPackage()
		for _, m := range f.GetMessageType() {
			indexMessage(messages, pkg, "", m)
		}
	}
	return messages
}

func (a *analyzer) checkMethod(fileName, pkg string, svc *descriptorpb.ServiceDescriptorProto, method *descriptorpb.MethodDescriptorProto) []string {
	methodRef := fmt.Sprintf("%s:%s.%s/%s", fileName, pkg, svc.GetName(), method.GetName())
	unknown := protooptions.MethodUnknown(method)

	hasHTTP := protooptions.HasExtension(unknown, protooptions.ExtGoogleHTTP)
	authzPayloads := protooptions.FindExtensionPayloads(unknown, protooptions.ExtAuthz)
	auditPayloads := protooptions.FindExtensionPayloads(unknown, protooptions.ExtAudit)
	hasAuthz := len(authzPayloads) > 0
	hasAudit := len(auditPayloads) > 0

	var diags []string
	if hasHTTP && !hasAuthz {
		diags = append(diags, methodRef+": external google.api.http method must declare aisphere.authz")
		return diags
	}
	if !hasAuthz {
		return diags
	}

	authz := protooptions.ParseAuthz(authzPayloads[len(authzPayloads)-1])
	if authz.Action == "" {
		diags = append(diags, methodRef+": aisphere.authz.action must not be empty")
	}
	if authz.Resource == "" {
		diags = append(diags, methodRef+": aisphere.authz.resource must not be empty")
	}
	if authz.Audience == "" {
		diags = append(diags, methodRef+": aisphere.authz.audience must not be empty")
	}
	if authz.Mode == 0 {
		diags = append(diags, methodRef+": aisphere.authz.mode must not be AUTHZ_MODE_UNSPECIFIED")
	}

	if isHighRiskAction(authz.Action, a.config.HighRiskActions) && !hasAudit {
		diags = append(diags, methodRef+": high-risk authz action "+quote(authz.Action)+" must declare aisphere.audit")
	}
	if hasAudit {
		audit := protooptions.ParseAudit(auditPayloads[len(auditPayloads)-1])
		if audit.Event == "" {
			diags = append(diags, methodRef+": aisphere.audit.event must not be empty")
		}
		if audit.Risk == "" && isHighRiskAction(authz.Action, a.config.HighRiskActions) {
			diags = append(diags, methodRef+": high-risk authz action "+quote(authz.Action)+" should set aisphere.audit.risk")
		}
	}

	if authz.Resource != "" {
		input := strings.TrimPrefix(method.GetInputType(), ".")
		msg := a.messages[input]
		for _, fieldPath := range templateFields(authz.Resource) {
			if msg == nil || !a.messageHasFieldPath(msg, fieldPath) {
				diags = append(diags, methodRef+": authz resource template references missing request field {"+fieldPath+"}")
			}
		}
	}
	return diags
}

func skipFile(name string) bool {
	return strings.HasPrefix(name, "third_party/") ||
		strings.HasPrefix(name, "vendor/") ||
		strings.Contains(name, "/internal/testdata/") ||
		strings.HasPrefix(name, "internal/testdata/") ||
		strings.Contains(name, "/testdata/") ||
		strings.HasSuffix(name, "aisphere/options/v1/authz.proto")
}

func indexMessage(out map[string]*descriptorpb.DescriptorProto, pkg, prefix string, m *descriptorpb.DescriptorProto) {
	name := strings.Trim(strings.Join(nonEmpty(pkg, prefix, m.GetName()), "."), ".")
	out[name] = m
	for _, nested := range m.GetNestedType() {
		indexMessage(out, pkg, strings.Trim(strings.Join(nonEmpty(prefix, m.GetName()), "."), "."), nested)
	}
}

func nonEmpty(values ...string) []string {
	out := make([]string, 0, len(values))
	for _, v := range values {
		if v != "" {
			out = append(out, v)
		}
	}
	return out
}

func splitCSV(s string) []string {
	parts := strings.Split(s, ",")
	out := make([]string, 0, len(parts))
	for _, p := range parts {
		p = strings.TrimSpace(strings.ToLower(p))
		if p != "" {
			out = append(out, p)
		}
	}
	return out
}

func isHighRiskAction(action string, tokens []string) bool {
	action = strings.ToLower(action)
	for _, token := range tokens {
		if token != "" && strings.Contains(action, token) {
			return true
		}
	}
	return false
}

var fieldRefRe = regexp.MustCompile(`\{([a-zA-Z_][a-zA-Z0-9_]*(?:\.[a-zA-Z_][a-zA-Z0-9_]*)*)\}`)

func templateFields(resource string) []string {
	matches := fieldRefRe.FindAllStringSubmatch(resource, -1)
	out := make([]string, 0, len(matches))
	seen := map[string]bool{}
	for _, m := range matches {
		if len(m) > 1 && !seen[m[1]] {
			seen[m[1]] = true
			out = append(out, m[1])
		}
	}
	return out
}

func (a *analyzer) messageHasFieldPath(m *descriptorpb.DescriptorProto, path string) bool {
	cur := m
	parts := strings.Split(path, ".")
	for i, part := range parts {
		field := findField(cur, part)
		if field == nil {
			return false
		}
		if i == len(parts)-1 {
			return true
		}
		if field.GetType() != descriptorpb.FieldDescriptorProto_TYPE_MESSAGE {
			return false
		}
		next := a.messages[strings.TrimPrefix(field.GetTypeName(), ".")]
		if next == nil {
			return false
		}
		cur = next
	}
	return true
}

func findField(m *descriptorpb.DescriptorProto, name string) *descriptorpb.FieldDescriptorProto {
	for _, f := range m.GetField() {
		if f.GetName() == name || f.GetJsonName() == name || snakeToCamel(name) == f.GetJsonName() || strings.EqualFold(name, f.GetJsonName()) {
			return f
		}
	}
	return nil
}

func snakeToCamel(s string) string {
	var b bytes.Buffer
	upper := false
	for i, r := range s {
		if r == '_' || r == '-' {
			upper = true
			continue
		}
		if i == 0 {
			b.WriteRune(r)
			continue
		}
		if upper && r >= 'a' && r <= 'z' {
			r = r - 'a' + 'A'
		}
		upper = false
		b.WriteRune(r)
	}
	return b.String()
}

func quote(s string) string {
	if s == "" {
		return "<empty>"
	}
	return fmt.Sprintf("%q", s)
}
